eff_capacity(G,Y) :- generator(G),const(cg,Y), ok(G).
eff_capacity(G,X) :- generator(G),const(cg,Y), needs_maintenance(G), X = Y - 5.

p(G,op,X) :- generator(G), c(G,is,running), c(G,id,X), eff_capacity(g, MAX), X <= MAX, not ab(G).
p(G,op,MAX) :- generator(G), c(G,is,running), c(G,id,X), eff_capacity(g, MAX), X > MAX, not ab(G).

p(G,op,0) :- generator(G), c(G,is,not_running), not ab(G), ok(G).
p(G,op,0) :- generator(G), c(G,is,not_running), not ab(G), needs_maintenance(G).
