% test 3 for substation

% load: 5
% external power: 5
% battery power: 0
% generator: not_running
% generator power: 0

% exp. result: output of 5

substation(s).

c(s,il,5).
p(s,ipext,5).
p(s,ipb,0).
c(s,ig,not_running).
p(s,ipg,0).

expect_c(s,il,5).
expect_p(s,ipext,5).
expect_p(s,ipb,0).
expect_c(s,ig,not_running).
expect_p(s,ipg,0).

expect_p(s,ops,5).
expect_p(s,opb,0).
expect_c(s,odg,0).
expect_c(s,odb,0).
